//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VrRos2Bridge
{
    [Serializable]
    public class ControllersInfoMsg : Message
    {
        public const string k_RosMessageName = "vr_ros2_bridge_msgs/ControllersInfo";
        public override string RosMessageName => k_RosMessageName;

        public ControllerInfoMsg[] controllers_info;

        public ControllersInfoMsg()
        {
            this.controllers_info = new ControllerInfoMsg[0];
        }

        public ControllersInfoMsg(ControllerInfoMsg[] controllers_info)
        {
            this.controllers_info = controllers_info;
        }

        public static ControllersInfoMsg Deserialize(MessageDeserializer deserializer) => new ControllersInfoMsg(deserializer);

        private ControllersInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.controllers_info, ControllerInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.controllers_info);
            serializer.Write(this.controllers_info);
        }

        public override string ToString()
        {
            return "ControllersInfoMsg: " +
            "\ncontrollers_info: " + System.String.Join(", ", controllers_info.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
