//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VrRos2Bridge
{
    [Serializable]
    public class TrackerInfoMsg : Message
    {
        public const string k_RosMessageName = "vr_ros2_bridge_msgs/TrackerInfo";
        public override string RosMessageName => k_RosMessageName;

        public string tracker_name;
        public Geometry.PoseMsg tracker_pose;

        public TrackerInfoMsg()
        {
            this.tracker_name = "";
            this.tracker_pose = new Geometry.PoseMsg();
        }

        public TrackerInfoMsg(string tracker_name, Geometry.PoseMsg tracker_pose)
        {
            this.tracker_name = tracker_name;
            this.tracker_pose = tracker_pose;
        }

        public static TrackerInfoMsg Deserialize(MessageDeserializer deserializer) => new TrackerInfoMsg(deserializer);

        private TrackerInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tracker_name);
            this.tracker_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tracker_name);
            serializer.Write(this.tracker_pose);
        }

        public override string ToString()
        {
            return "TrackerInfoMsg: " +
            "\ntracker_name: " + tracker_name.ToString() +
            "\ntracker_pose: " + tracker_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
